"use client";

import { useCallback, useRef, useState } from "react";
import { useAuth } from "@/components/AuthProvider";

/**
 * A rich image record returned by GET /api/admin/gallery.
 * Now powered by Firestore `mediaLibrary` instead of Storage listing —
 * includes all variant URLs, blur placeholder, and original image dimensions.
 */
export interface GalleryItem {
  /** Firestore document ID — used as the pagination cursor */
  id: string;
  /** path relative to the products/ root — ready to store on a product gallery */
  path: string;
  /** full storage object key — kept for backwards compat */
  name: string;
  prefix: string;
  /** Primary display URL (full 1200px WebP) */
  url: string;
  /** Optimized WebP variant URLs generated by Sharp at upload time */
  thumbUrl:   string;
  mediumUrl:  string;
  fullUrl:    string;
  /** Base64 micro-placeholder for blur-up effect */
  blurDataURL: string;
  /** Original image dimensions for correct Next.js <Image> width/height */
  originalWidth:  number | null;
  originalHeight: number | null;
  /** File metadata */
  fileSizeBytes:    number;
  contentType:      string;
  originalFileName: string;
  /** Audit fields */
  uploadedAt:  string | null;
  uploadedBy:  string;
  /** Legacy compat — kept so existing consumers don't break */
  size:    number;
  updated: string | null;
}

/**
 * Cursor-paginated reader for GET /api/admin/gallery.
 * Backed by Firestore `mediaLibrary` — sorted newest-first, much faster than
 * listing Storage objects. Pagination uses Firestore doc IDs as cursors.
 */
export function useGallery(prefix = "", limit = 60) {
  const { getToken } = useAuth();
  const [images, setImages] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError]     = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(true);
  // Firestore cursor: the Firestore doc ID of the last item on the current page
  const cursor = useRef<string | null>(null);

  const load = useCallback(
    async (reset = false) => {
      setLoading(true);
      setError(null);
      try {
        const token = await getToken();
        if (reset) cursor.current = null;
        const params = new URLSearchParams({ prefix, limit: String(limit) });
        // Use lastDocId for Firestore cursor pagination (replaces old pageToken)
        if (cursor.current) params.set("lastDocId", cursor.current);
        const res = await fetch(`/api/admin/gallery?${params.toString()}`, {
          headers: { authorization: `Bearer ${token}` },
        });
        const j = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(j.error || "Failed to load images");
        // nextPageToken is now the last Firestore doc ID
        cursor.current = j.nextPageToken ?? null;
        setHasMore(Boolean(j.nextPageToken));
        setImages((prev) => (reset ? j.images : [...prev, ...j.images]));
      } catch (e) {
        const errorMsg = (e as Error).message;
        console.error("[Gallery] Error:", errorMsg, "Token:", token ? "present" : "null");
        setError(errorMsg);
      } finally {
        setLoading(false);
      }
    },
    [getToken, prefix, limit],
  );

  return { images, loading, error, hasMore, load };
}

