"use client";

import { useCallback, useRef, useState } from "react";
import { useAuth } from "@/components/AuthProvider";

/**
 * A rich image record returned by GET /api/admin/gallery.
 * Powered by the `media_library` table instead of Storage listing —
 * includes all variant URLs, blur placeholder, and original image dimensions.
 */
export interface GalleryItem {
  /** media_library row ID */
  id: string;
  /** path relative to the products/ root — ready to store on a product gallery */
  path: string;
  /** full storage object key — kept for backwards compat */
  name: string;
  prefix: string;
  /** Primary display URL (full 1200px WebP) */
  url: string;
  /** Optimized WebP variant URLs generated by Sharp at upload time */
  thumbUrl:   string;
  mediumUrl:  string;
  fullUrl:    string;
  /** Base64 micro-placeholder for blur-up effect */
  blurDataURL: string;
  /** Original image dimensions for correct Next.js <Image> width/height */
  originalWidth:  number | null;
  originalHeight: number | null;
  /** File metadata */
  fileSizeBytes:    number;
  contentType:      string;
  originalFileName: string;
  /** Audit fields */
  uploadedAt:  string | null;
  uploadedBy:  string;
  /** Legacy compat — kept so existing consumers don't break */
  size:    number;
  updated: string | null;
}

/**
 * Cursor-paginated reader for GET /api/admin/gallery.
 * Backed by the `media_library` table — sorted newest-first. The pagination
 * token is opaque to this hook; the API echoes the next one via nextPageToken.
 */
export function useGallery(prefix = "", limit = 60) {
  const { getToken } = useAuth();
  const [images, setImages] = useState<GalleryItem[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError]     = useState<string | null>(null);
  const [hasMore, setHasMore] = useState(true);
  // Opaque pagination token from the previous page's response
  const cursor = useRef<string | null>(null);

  /** Patch one image in place (e.g. after a rotate) without refetching. */
  const patch = useCallback((id: string, updates: Partial<GalleryItem>) => {
    setImages((prev) => prev.map((img) => (img.id === id ? { ...img, ...updates } : img)));
  }, []);

  const load = useCallback(
    async (reset = false) => {
      setLoading(true);
      setError(null);
      try {
        const token = await getToken();
        if (reset) cursor.current = null;
        const params = new URLSearchParams({ prefix, limit: String(limit) });
        if (cursor.current) params.set("lastDocId", cursor.current);
        const res = await fetch(`/api/admin/gallery?${params.toString()}`, {
          headers: { authorization: `Bearer ${token}` },
        });
        const j = await res.json().catch(() => ({}));
        if (!res.ok) throw new Error(j.error || "Failed to load images");
        cursor.current = j.nextPageToken ?? null;
        setHasMore(Boolean(j.nextPageToken));
        setImages((prev) => (reset ? j.images : [...prev, ...j.images]));
      } catch (e) {
        setError((e as Error).message);
      } finally {
        setLoading(false);
      }
    },
    [getToken, prefix, limit],
  );

  return { images, loading, error, hasMore, load, patch };
}

